class CompRunner

{
public static void main(String[] args)
{
Helicopter helicopter=new Helicopter();
Helicopter helicopter1=new Helicopter();
Helicopter helicopter2=new Helicopter();
Helicopter helicopter3=new Helicopter();
Helicopter helicopter4=new Helicopter();

Market market=new Market();
Market market1=new Market() ;
Market market2=new Market() ;
Market market3=new Market() ;
Market market4=new Market();

Mall mall=new Mall();
Mall mall1=new Mall();
Mall mall2=new Mall();
Mall mall3=new Mall();
Mall mall4=new Mall();

Train train=new Train();
Train train1=new Train();
Train train2=new Train();
Train train3=new Train();
Train train4=new Train();

Ring ring=new Ring();
Ring ring1=new Ring();
Ring ring2=new Ring();
Ring ring3=new Ring();
Ring ring4=new Ring();

Auto auto=new Auto();
Auto auto1=new Auto();
Auto auto2=new Auto();
Auto auto3=new Auto();
Auto auto4=new Auto();

SpaceShip spaceShip=new SpaceShip();
SpaceShip spaceShip1=new SpaceShip();
SpaceShip spaceShip2=new SpaceShip();
SpaceShip spaceShip3=new SpaceShip();
SpaceShip spaceShip4=new SpaceShip();

Alien alien=new Alien();
Alien alien1=new Alien();
Alien alien2=new Alien();
Alien alien3=new Alien();
Alien alien4=new Alien();

Bullet bullet=new Bullet();
Bullet bullet1=new Bullet();
Bullet bullet2=new Bullet();
Bullet bullet3=new Bullet();
Bullet bullet4=new Bullet();

Galaxy galaxy=new Galaxy();
Galaxy galaxy1=new Galaxy();
Galaxy galaxy2=new Galaxy();
Galaxy galaxy3=new Galaxy();
Galaxy galaxy4=new Galaxy();

Spoon spoon=new Spoon();
Spoon spoon1=new Spoon();
Spoon spoon2=new Spoon();
Spoon spoon3=new Spoon();
Spoon spoon4=new Spoon();

BlackHole blackHole=new BlackHole();
BlackHole blackHole1=new BlackHole();
BlackHole blackHole2=new BlackHole();
BlackHole blackHole3=new BlackHole();
BlackHole blackHole4=new BlackHole();

Cake cake =new Cake();
Cake cake1 =new Cake();
Cake cake2 =new Cake();
Cake cake3 =new Cake();
Cake cake4 =new Cake();

Wrapper wrapper=new Wrapper();
Wrapper wrapper1=new Wrapper();
Wrapper wrapper2=new Wrapper();
Wrapper wrapper3=new Wrapper();
Wrapper wrapper4=new Wrapper();


}
}

