class BloodGroupConcatenation
{
public static void main(String[] args)
{
String name="pavan";
System.out.println(pavan);
String surname="kalal";
String x=name+"surname";
String gmail="pavan123@gmail.com";
System.out.println(gmail);
String password="pavan123";
System.out.println(password);
String shirtsize="XL";
System.out.println(shirtsize);
String address="No 712/55, 62st Cross, 5th Block, Rajajinagar, Bengaluru, Karnataka 560010";
System.out.println(address);
String shoesSize="5";
System.out.println(shoesSize);
String marks="600";
System.out.println(marks);
String brother="ram & laxman";
System.out.println(brother);
String bloodGroup="B+";
System.out.println(bloodGroup);
String food="Rice,chapati,dal,dose";
System.out.println(food);
String datatypes="primitive and non primitive";
System.out.println(datatypes);
String keywords="total 48 keywords there in java";
System.out.println(keywords);
String water="500 litre";
System.out.println(water);
String pointer="pointer*500";
System.out.println(pointer);
String Engineer="Engineer is solve problems in real world is called Engineer";
System.out.println(Engineer);
String trees="Go green";
System.out.println(trees);
String subjects="maths,physics,chemistry";
System.out.println(subjects);
String chappalSize="4";
System.out.println(chappalSize);
String notes="Oracle java";
System.out.println(notes);
String car="Tesla,BMW,thar";
System.out.println(car);
String computer="computer is hardware device";
System.out.println(computer);
String specialcharactors="!@#$%^&*()_+";
System.out.println(specialcharactors);
String phonenumber="9980693020";
System.out.println(phonenumber);
String pincode="585214";
System.out.println(pincode);
String program="Hello World";
System.out.println(program);
String count="1,2,3,4,5,6,7,8,9";
System.out.println(count);
String complexity="O(log n)";
System.out.println(complexity);
String university="Sharnabasava University";
System.out.println(university);
String hobby="cooking different dish";
System.out.println(hobby);
String course="Full stack web development";
System.out.println(course);
String distance="6545 km";
System.out.println(distance);
String area="Rajajinagar";
System.out.println(area);
String instagramaccount="renukakalal_";
System.out.println(instagramaccount);
String tags="#trending#argitsingh#film#songs#kalki";
System.out.println(tags);
String percentage="35%";
System.out.println(percentage);
String hallticketNo="F2R3573";
System.out.println(hallticketNo);
String busNo="KA32653433";
System.out.println(busNo);
String price="9999 Rs";
System.out.println(price);
String time="02:18 PM";
System.out.println(time);
String date="28-06-2024";
System.out.println(date);
String cricket="IND vs END";
System.out.println(cricket);
String speed="25km/hour";
System.out.println(speed);
String file="notepad++";
System.out.println(file);
String weather="today is cloudy";
System.out.println(weather);
String temprature="45 degree Celcius";
System.out.println(temprature);
String array="it is used to store set of elements";
System.out.println(array);
String calculator="+ -   *  % /  ";
System.out.println(calculator);
String movie="kalki";
System.out.println(movie);
String battery="5 V";
System.out.println(battery);
String eP="Q4πε0r2";
System.out.println(eP);
String v="14πε0∑Qiri";
System.out.println(v);
String eExt="△KE+ΔU";
System.out.println(eExt);
String f="14πϵq1q2r212r12";
System.out.println( f);
String ram="8GB";
System.out.println(ram);
String americandoller="$";
System.out.println(americandoller);
String operatingsystem="window 11";
System.out.println(operatingsystem);
String pivalue="3.14";
System.out.println(pivalue);
String railwaytiming="13:15:09";
System.out.println(railwaytiming);
String companyname="Reliance Industries";
System.out.println(companyname);
String dateandtime="25/06/2024 and 04:14:00";
System.out.println(dateandtime);
String city="jaipur known as pink city";
System.out.println(city);
String animal="lion is king of jungle";
System.out.println(animal);
String rcb="royal challengers bengaluru";
System.out.println(rcb);
String diameter="67.24 meter/sq";
System.out.println(diameter);
String cell="mitochondria is power of cell";  
System.out.println(cell);
String string="sequence of charactor";
System.out.println(string);
String doorNo="53";
System.out.println(doorNo);
String matrix="[5][7][7][8]";
System.out.println(matrix);
String integratin="{dy/dx";
System.out.println( integratin);
String pythogorustherom="a^2+b^2+2ab";
System.out.println(pythogorustherom);
}
}
